####
#
#	tinyos/test
#
$super_script = <<SSCRIPT
export DEBIAN_FRONTEND=noninteractive

wget -O - http://tinyprod.net/repos/debian/tinyprod.key | sudo apt-key add -
#gpg --keyserver keyserver.ubuntu.com --recv-keys A9B913B9
#gpg -a --export A9B913B9 | sudo apt-key add -

sudo echo "deb http://tinyprod.net/repos/debian wheezy main" >> /etc/apt/sources.list.d/tinyprod-debian.list
sudo echo "deb http://tinyprod.net/repos/debian msp430-46 main" >> /etc/apt/sources.list.d/tinyprod-debian.list

DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install nesc tinyos-tools-devel msp430-46 mspdebug -qy --force-yes
SSCRIPT

$script = <<SCRIPT
mkdir -p ~/top
cd ~/top
mkdir t2_cur
cd t2_cur
git clone -v git://github.com/tp-freeforall/prod tinyos-2.x
cd tinyos-2.x

read -d '' PROFILE_SNIPPET <<"EOF"
export MOTECOM="serial@/dev/ttyUSB0:telosb"
export TINYOS_ROOT_DIR=~/top/t2_cur/tinyos-2.x
export CLASSPATH=.:$TINYOS_ROOT_DIR/support/sdk/java/tinyos.jar
export PYTHONPATH=$TINYOS_ROOT_DIR/support/sdk/python:$PYTHONPATH
export MSPDEBUG_TI3410_FW=/usr/lib/mspdebug
EOF
echo "$PROFILE_SNIPPET" | tee -a /home/vagrant/.profile
sudo gpasswd -a vagrant dialout
sudo gpasswd -a vagrant plugdev
SCRIPT

$host_name = "tinyos-test"

Vagrant.configure(2) do |config|
	config.vm.hostname = $host_name
 	config.vm.box = 'tinyos/basic'
	config.ssh.forward_agent = true

	config.vm.provider 'virtualbox' do |vb|
		vb.name = $host_name
#		vb.gui = true
	    vb.customize ["modifyvm", :id, "--memory", 1024]
    	vb.customize ["modifyvm", :id, "--vram", 64]
    	vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
		vb.customize ["modifyvm", :id, "--usb", "on"]
		vb.customize ["modifyvm", :id, "--usbehci", "on"]
		vb.customize ["usbfilter", "add", "0", 
						"--target", :id, 
						"--name", "msp_debugger",
						"--manufacturer", "Texas Instruments",
						"--product", "MSP-FET430UIF JTAG Tool"]
  end

  config.vm.provision 'shell', inline: $super_script
  config.vm.provision 'shell', privileged: false, inline: $script
end
