# -*- mode: ruby -*-
# vi: set ft=ruby :

$box_name = "user-vm-32"

$modify_bashrc = <<SCRIPT
cd ~

if [ ! -e ~/.bashrc_env ] ; then
cat >> ~/.bashrc <<EOF
. ~/.bashrc_env
EOF

cat > ~/.bashrc_env <<EOF
if [ -z \\\$TINYOS_ENV_SET ] ; then
	export NEW_HOME=/home/vagrant
	export DEV_ROOT=\\\$NEW_HOME/msp430dev
	export MM_ROOT=\\\$DEV_ROOT/mm
	export TINYOS_ROOT_DIR=\\\$DEV_ROOT/prod
	export TINYOS_ROOT_DIR_ADDITIONAL=\\\$MM_ROOT:\\\$TINYOS_ROOT_DIR_ADDITIONAL
	export CLASSPATH=.:\\\$TINYOS_ROOT_DIR/support/sdk/java/tinyos.jar
	export PYTHONPATH=\\\$TINYOS_ROOT_DIR/support/sdk/python:\\\$PYTHONPATH
	export PYTHONPATH=/usr/local/lib/python3.4/dist-packages:\\\$PYTHONPATH
	export TINYOS_ENV_SET="true"
fi
EOF
fi

. ~/.bashrc_env
if [ ! -e $DEV_ROOT ] ; then
    mkdir $DEV_ROOT
    cd $DEV_ROOT
    git clone -v git://github.com/tp-freeforall/prod
    git clone -v git://github.com/MamMark/mm.git
    cd ~
fi

cd $MSP/prod/apps/Blink
make debugopt telosb
make debugopt exp5438_gps
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu_dev/msp430"
  config.vm.box_url = 'http://www.tinyprod.net/boxes/ubuntu_dev-msp430.json'
  config.vm.box_download_checksum = '807306875e499c5443db534beda6202d77f04292b90b665751203978f3a9436a'
  config.vm.box_download_checksum_type = 'sha256'
  config.vm.box_check_update = false

  config.vm.define $box_name
  config.vm.hostname = $box_name

  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true

  config.vm.synced_folder "~/", "/home/vagrant/home"

  config.vm.network "public_network", bridge: ""

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = $box_name
    override.vm.provision :shell, privileged: false, inline: $modify_bashrc
  end
end
