####
#
#	ubuntu_dev/basic
#
$my_name = "u1404-dev-basic"

# super_script
#
$linux_script = <<SSCRIPT
export DEBIAN_FRONTEND=noninteractive

echo "UPDATING linux"
apt-get update

echo "*** UPGRADING distribution"
apt-get dist-upgrade -qy \
	-o Dpkg::Options::="--force-confdef" \
	-o Dpkg::Options::="--force-confold" 

echo "*** INSTALLING build-essential git gitk"
echo "*** INSTALLING python python3 python-dev python-serial python3-serial "
echo "*** INSTALLING openjdk-7-jre openjdk-7-jdk  "
echo "*** INSTALLING libusb-dev libreadline-dev "
echo "*** INSTALLING linux-headers-generic linux-image-extra-virtual linux-firmware "
echo "*** INSTALLING emacs emacs24-el tree"
				
apt-get install -qy --force-yes \
	build-essential git gitk\
	python python3 python-dev python-serial python3-serial \
	openjdk-7-jre openjdk-7-jdk \
	libusb-dev libreadline-dev \
	linux-headers-generic linux-image-extra-virtual linux-firmware \
	emacs emacs24-el tree

#echo "*** ? stow automake autoconf libtool libc6-dev"
#echo "*** ? git-core git-daemon-run git-doc git-email git-gui gitmagic"
#echo "*** ? openssh-client openssh-server vim aptitude"
SSCRIPT

Vagrant.configure(2) do |config|
	config.vm.box = 'trusty32'
	config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/20151021/trusty-server-cloudimg-i386-vagrant-disk1.box'
	config.vm.box_download_checksum = '4c62640a75a57be45b9afe20f25f6e5ada0f98cf3765cd4b5e7501d0adc7d0b2'
	config.vm.box_download_checksum_type = 'sha256'

	config.ssh.insert_key = false

	config.vm.provision 'shell', inline: $linux_script  
	config.vm.provision "shell", path: "../common/compact.sh"

	config.vm.define $my_name do |config|
		config.vm.hostname = $my_name
		config.vm.provider 'virtualbox' do |vb, override|
			vb.name = $my_name
			override.vm.synced_folder "~/", "/home/vagrant/home" # optional, useful for rapid development
	        vb.customize ["modifyvm", :id, "--memory", 1024]
		end
	end
end
