####
#
#	tinyos/mammap2
#
$load_script = <<LSCRIPT
export DEBIAN_FRONTEND=noninteractive
git clone git://git.code.sf.net/p/mspdebug/code mspdebug
cd mspdebug
make
sudo make install
LSCRIPT

#usbserial, ti_usb_3410_5052

$host_name = "tinyos-mammap2"

Vagrant.configure(2) do |config|
 	config.vm.box = 'tinyos/basic'
	config.vm.hostname = $host_name
	config.ssh.forward_agent = true

	config.vm.provider 'virtualbox' do |vb, override|
		vb.name = $host_name
		vb.gui = true
		override.vm.synced_folder "~/", "/home/vagrant/home"
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--vram", 64]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
		# usb device
		vb.customize ["modifyvm", :id, "--usb", "on"]
		vb.customize ["modifyvm", :id, "--usbehci", "on"]
		vb.customize ["usbfilter", "add", "0", 
						"--target", :id, 
						"--name", "msp_jtag_debugger",
						"--manufacturer", "Texas Instruments",
						"--product", "MSP-FET430UIF JTAG Tool"]
  end

#  config.vm.provision 'shell', privileged: false, inline: $load_script
end
