####
#
#	tinyos/mammap2
#
$name = "tinyos-mammap2"

Vagrant.configure(2) do |config|
	config.vm.hostname = $name
 	config.vm.box = 'trusty'
	config.ssh.forward_agent = true
	config.vm.provision :shell, path: "../common/msp430_tools_install.sh"

	config.vm.provider 'virtualbox' do |vb, override|
		vb.name = $name
		override.vm.synced_folder "~/", "/home/vagrant/home"
        vb.customize ["modifyvm", :id, "--memory", 1024]

		# add filter for TI JTAG usb device
		vb.customize ["modifyvm", :id, "--usb", "on"]
		vb.customize ["modifyvm", :id, "--usbehci", "on"]
		vb.customize ["usbfilter", "add", "0", 
						"--target", :id, 
						"--name", "msp430_jtag_debugger",
						"--manufacturer", "Texas Instruments",
						"--product", "MSP-FET430UIF JTAG Tool"]
	end
end
#  config.vm.box = 'trusty'
#  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/20151021/trusty-server-cloudimg-i386-vagrant-disk1.box'
#  config.vm.box = 'box-cutter/ubuntu1404-desktop'
#  config.vm.box_download_checksum = '4c62640a75a57be45b9afe20f25f6e5ada0f98cf3765cd4b5e7501d0adc7d0b2'
#  config.vm.box_download_checksum_type = 'sha256'
# *trusty-server-cloudimg-i386-vagrant-disk1.box
