####
#
#	tinyos/mammap
#
$name = "tinyos-mammap"

Vagrant.configure(2) do |config|
	config.vm.hostname = $name
 	config.vm.box = 'tinyos/basic'
	config.ssh.forward_agent = true
	config.vm.provision :shell, path: "../common/msp430_tools_install.sh"

	config.vm.provider 'virtualbox' do |vb, override|
		vb.name = $name
		override.vm.synced_folder "~/", "/home/vagrant/home"
        vb.customize ["modifyvm", :id, "--memory", 1024]
		# add graphics display (for workstation)
		#vb.gui = true
        #vb.customize ["modifyvm", :id, "--vram", 64]
        #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
		# add filter for TI JTAG usb device
		vb.customize ["modifyvm", :id, "--usb", "on"]
		vb.customize ["modifyvm", :id, "--usbehci", "on"]
		vb.customize ["usbfilter", "add", "0", 
						"--target", :id, 
						"--name", "msp430_jtag_debugger",
						"--manufacturer", "Texas Instruments",
						"--product", "MSP-FET430UIF JTAG Tool"]
	end
end
