# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#	ubuntu_dev/mammap
#
$my_name = "ubuntu-dev-mammap"

# script
#
$script = <<SCRIPT
echo "*** HELLO"
SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = $my_name
  config.vm.box = "ubuntu_dev/msp430"
  
  config.vm.provision :shell, inline: $script

  config.vm.provider "virtualbox" do |vb, override|
	vb.name = $my_name
    override.vm.synced_folder "~/", "/home/vagrant/home"
    
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ['modifyvm', :id, '--usb', 'on']
    
  end
end
